// GENERATED by scripts/build-wire-types.mjs — DO NOT EDIT.
// Source of truth: schemas/*.json. scripts/validate.mjs enforces freshness.
//
// These are the STRUCTURAL PROJECTIONS of the wire schemas: shape,
// requiredness, literals, tuples, unions. Patterns, length bounds,
// if/then/else, `not`, `contains`, `dependentRequired` and uniqueItems
// are NOT expressible here and remain normative in the schemas alone —
// satisfying a type is necessary for conformance, never sufficient.
// Validate against SCHEMAS before treating any value as a wire artifact.
import type { Json } from './core.js'

/** schemas/access-material.schema.json — RLTP Access key material (Access Layer 0.55 sections 9.4, 9.4.1, 9.4.2) */
export type AccessMaterial = ({
  v: "rltp-access-material/0.25" | "rltp-access-keydist/0.25"
  adapter: "linear/0.1" | "beekem/0.1"
  epoch: number
  keyState?: string
  keys: { [k: string]: Json }
})

/** schemas/access-operation-envelope.schema.json — RLTP Access Operation Envelope (transcription of Access Layer 0.55 section 3.3, envelope rltp-access/0.25) */
export type AccessOperationEnvelope = ({
  v: "rltp-access/0.25"
  op: string
  group: string
  epoch: number
  policyVersion: number
  prev: string[]
  body: { [k: string]: Json }
  crit?: string[]
  id: string
  author: string
  proof: ({
    mechanism: "signature-set" | "encounter-presentation" | "composite"
    signatures?: {
      signer: string
      sig: string
    }[]
    credentials?: { [k: string]: Json }[]
  })
})

/** schemas/access-registration.schema.json — RLTP Service Registration (artifact 0.27, Access Layer section 7.3) */
export type AccessRegistration = ({
  v: "rltp-access-registration/0.27"
  type: "service-registration"
  group: string
  genesisDigest: string
  identity: string
  service: string
  m: 1
  class: "blind" | "view" | "log"
  stalenessBound: string
  terminalRetention: string
  divergenceQuota: number
  intakeBudget?: {
    operations: number
    bytes: number
  }
  sig: string
  attestationKey: string
  registrationGeneration: number
  previousRegistration: (null) | (string)
  authorization?: {
    signer: string
    sig: string
  }[]
  abandon?: {
    abandonedRoot: string
    abandonedTipsDigest: string
  }
  authorizationRoot: (null) | (string)
})

/** schemas/access-vouch.schema.json — DTG AdmissionVouch (vouch@2, Access Layer 0.55 section 5.3) */
export type AccessVouch = {
  "@context": ["https://www.w3.org/ns/credentials/v2", "https://firstperson.network/credentials/dtg/v1", "https://real-life.org/rltp/v1"]
  type: (Json[])
  issuer: string
  validFrom: string
  credentialSubject: {
    id: string
    endorsement: {
      type: "AdmissionVouch"
      genesisDigest: string
      accept: string
      provenance: "met" | "introduced"
    }
  }
  proof: {
    type: "DataIntegrityProof"
    cryptosuite: "eddsa-jcs-2022"
    created: string
    verificationMethod: string
    proofPurpose: "assertionMethod"
    proofValue: string
    "@context": ["https://www.w3.org/ns/credentials/v2", "https://firstperson.network/credentials/dtg/v1", "https://real-life.org/rltp/v1"]
  }
}

/** schemas/authorization-view.schema.json — RLTP Authorization View (Access Layer 0.24 section 7.3) */
export type AuthorizationView = ({
  v: "rltp-access-view/0.24"
  type: "authorization-view"
  group: string
  genesisDigest: string
  seq: number
  epoch: number
  identities: string[]
  m: (null) | (number)
  terminal: boolean
  prevView: (null) | (string) | (string[])
  predecessor?: string
  issuedAt: string
  validUntil: string
  sigs: {
    signer: string
    sig: string
  }[]
})

/** schemas/carrier-proof.schema.json — RLTP Carrier Registration Proof (rltp-carrier-proof/0.3, rltp-delivery@0.79) */
export type CarrierProof = ({
  v: "rltp-carrier-proof/0.3"
  type: "carrier-registration-proof"
  purpose: "register" | "rebind" | "collect" | "conclude"
  carrier: string
  principal: string
  rkid: string
  generation?: number
  principalChallenge: string
  addressChallenge?: string
  sig: string
})

/** schemas/contact-card-0.25.schema.json — RLTP Contact Card (rltp-encounter@0.30) */
export type ContactCard025 = {
  version: "rltp-card/0.25"
  anchor: string
  keyAgreement: string
  challenge?: {
    value: string
    issuedAt: string
  }
  sentTo?: string
  boundTo?: string
  name?: string
  deliveryHints?: string[]
  proof: {
    type: "DataIntegrityProof"
    cryptosuite: "eddsa-jcs-2022"
    created: string
    verificationMethod: string
    proofPurpose: "assertionMethod"
    proofValue: string
  }
}

/** schemas/contact-card.schema.json — RLTP Contact Card (rltp-encounter@0.30) — mobile $id, carried by the unversioned resource */
export type ContactCard = {
  version: "rltp-card/0.25"
  anchor: string
  keyAgreement: string
  challenge?: {
    value: string
    issuedAt: string
  }
  sentTo?: string
  boundTo?: string
  name?: string
  deliveryHints?: string[]
  proof: {
    type: "DataIntegrityProof"
    cryptosuite: "eddsa-jcs-2022"
    created: string
    verificationMethod: string
    proofPurpose: "assertionMethod"
    proofValue: string
  }
}

/** schemas/encounter-credential-0.25.schema.json — RLTP Encounter Credential (rltp-encounter@0.30) */
export type EncounterCredential025 = {
  "@context": ["https://www.w3.org/ns/credentials/v2", "https://firstperson.network/credentials/dtg/v1", "https://real-life.org/rltp/v1"]
  type: (Json[])
  issuer: string
  validFrom: string
  credentialSubject: {
    id: string
    format: "rltp-encounter-credential/0.25"
    ceremony: string
    challenge: string
    enactmentBinding: string
    channel?: string
    commitment?: {
      suite: string
      value: string
    }
  }
  proof: {
    type: "DataIntegrityProof"
    cryptosuite: "eddsa-jcs-2022"
    created: string
    verificationMethod: string
    proofPurpose: "assertionMethod"
    proofValue: string
    "@context": ["https://www.w3.org/ns/credentials/v2", "https://firstperson.network/credentials/dtg/v1", "https://real-life.org/rltp/v1"]
  }
}

/** schemas/encounter-credential.schema.json — RLTP Encounter Credential (rltp-encounter@0.30) — mobile $id, carried by the unversioned resource */
export type EncounterCredential = {
  "@context": ["https://www.w3.org/ns/credentials/v2", "https://firstperson.network/credentials/dtg/v1", "https://real-life.org/rltp/v1"]
  type: (Json[])
  issuer: string
  validFrom: string
  credentialSubject: {
    id: string
    format: "rltp-encounter-credential/0.25"
    ceremony: string
    challenge: string
    enactmentBinding: string
    channel?: string
    commitment?: {
      suite: string
      value: string
    }
  }
  proof: {
    type: "DataIntegrityProof"
    cryptosuite: "eddsa-jcs-2022"
    created: string
    verificationMethod: string
    proofPurpose: "assertionMethod"
    proofValue: string
    "@context": ["https://www.w3.org/ns/credentials/v2", "https://firstperson.network/credentials/dtg/v1", "https://real-life.org/rltp/v1"]
  }
}

/** schemas/member-mapping.schema.json — RLTP member-mapping@1 (rltp-access-member-mapping/0.24) */
export type MemberMapping = {
  body: {
    type: "member-mapping@1"
    member: string
    memberOp: string
    self: string
    to: string
    toOp: string
    card: {
      body: {
        type: "self-card@1"
        anchor: string
        keyAgreement: string
      }
      proof: {
        proofValue: string
      }
    }
    revision: string
    issuedAt: string
  }
  proof: {
    mac1: string
    mac2: string
  }
}

/** schemas/payload-access-operation.schema.json — Payload: access-operation/0.1 (rltp-membership@0.17, target Trust Tasks framework 0.4) */
export type PayloadAccessOperation = ({
  operation: (AccessOperationEnvelope)
  welcome: {
    sealed: SealedEnvelope
  }
}) & ({
  operation?: {
    v: "rltp-access/0.25"
  }
}) & ({
  operation?: {
    op: "member.add"
    body?: Json
  }
}) & ({
  operation?: {
    proof?: {
      signatures?: Json
      credentials?: Json
    }
  }
})

/** schemas/payload-delivery-ack.schema.json — Payload: delivery-ack/0.1 (rltp-delivery@0.79, target Trust Tasks framework 0.4) */
export type PayloadDeliveryAck = {
  ref: string
  meaning: "received"
}

/** schemas/payload-encounter-bundle.schema.json — Payload: encounter-bundle/0.1 (rltp-delivery@0.79, target Trust Tasks framework 0.4) */
export type PayloadEncounterBundle = {
  card: ContactCard
  credential: EncounterCredential
}

/** schemas/payload-encounter-credential-delivery.schema.json — Payload: encounter-credential-delivery/0.1 (rltp-delivery@0.79, target Trust Tasks framework 0.4) */
export type PayloadEncounterCredentialDelivery = {
  credential: EncounterCredential
}

/** schemas/payload-key-delivery.schema.json — Payload: key-delivery/0.1 (rltp-access@0.55, target Trust Tasks framework 0.4) */
export type PayloadKeyDelivery = {
  keyDelivery: ({
    group: string
    genesisDigest: string
    subject: string
    epoch: number
    op?: string
    admission?: {
      subject: string
      acceptDigest: string
    }
    kind: "keydist" | "re-welcome" | "refresh" | "material" | "request"
    sealed?: SealedEnvelope
    card?: ({
      anchor: string
      device: string
      keyAgreement: string
      serviceIdentity: string
      proof: {
        signer: string
        sig: string
      }
    }) | (ContactCard)
  })
}

/** schemas/payload-membership-accept.schema.json — Payload: membership-accept/0.2 (rltp-membership@0.17, target Trust Tasks framework 0.4) */
export type PayloadMembershipAccept = {
  accept: {
    group: string
    subject: string
    ref: string
    card: ContactCard
    candidacy: boolean
  }
}

/** schemas/payload-membership-evidence-0.1.schema.json — Payload: membership-evidence/0.1 (rltp-membership@0.17, target Trust Tasks framework 0.4) */
export type PayloadMembershipEvidence01 = {
  evidence: {
    invite: (RltpDeliveryDocument) & ({
      type?: "https://real-life.org/trust-tasks/membership-invite/0.2"
      payload?: PayloadMembershipInvite
      proof?: never
    })
    accept: (RltpDeliveryDocument) & ({
      type?: "https://real-life.org/trust-tasks/membership-accept/0.2"
      payload?: PayloadMembershipAccept
    })
  }
}

/** schemas/payload-membership-evidence.schema.json — Payload: membership-evidence/0.2 (rltp-membership@0.17, target Trust Tasks framework 0.4) */
export type PayloadMembershipEvidence = {
  evidence: {
    invite: (RltpDeliveryDocument) & ({
      type?: "https://real-life.org/trust-tasks/membership-invite/0.2"
      payload?: PayloadMembershipInvite
      proof?: never
    })
    accept: (RltpDeliveryDocument) & ({
      type?: "https://real-life.org/trust-tasks/membership-accept/0.2"
      payload?: PayloadMembershipAccept
    })
    vouches?: AccessVouch[]
  }
}

/** schemas/payload-membership-invite.schema.json — Payload: membership-invite/0.2 (rltp-membership@0.17, target Trust Tasks framework 0.4) */
export type PayloadMembershipInvite = {
  invite: {
    "@context": ["https://www.w3.org/ns/credentials/v2", "https://firstperson.network/credentials/dtg/v1", "https://real-life.org/rltp/v1"]
    type: (Json[])
    issuer: string
    credentialSubject: {
      id: string
      group: string
      genesisDigest: string
      card: ContactCard
      name?: string
      note?: string
    }
    validFrom: string
    validUntil: string
    taskContext: string
    proof: {
      type: "DataIntegrityProof"
      cryptosuite: "eddsa-jcs-2022"
      created: string
      verificationMethod: string
      proofPurpose: "assertionMethod"
      proofValue: string
      "@context": ["https://www.w3.org/ns/credentials/v2", "https://firstperson.network/credentials/dtg/v1", "https://real-life.org/rltp/v1"]
    }
  }
}

/** schemas/payload-registry-declaration.schema.json — RLTP payload registry-declaration (rltp-delivery@0.79) */
export type PayloadRegistryDeclaration = {
  declaration: {
    role: string
    revision: string
    constants: { [k: string]: string }
  }
}

/** schemas/payload-removal-notice.schema.json — RLTP Removal Notice (Access Layer 0.55 section 10.2) */
export type PayloadRemovalNotice = {
  v: "rltp-access-removal-notice/0.25"
  type: "removal-notice"
  group: string
  genesisDigest: string
  op: string
  subject: string
  epoch: number
  author: string
  issuer: string
  sig: string
}

/** schemas/rltp-delivery-document.schema.json — RLTP Delivery Document Profile (rltp-delivery@0.79) */
export type RltpDeliveryDocument = ({
  id: string
  type: string
  issuer: string
  recipient: string
  threadId: string
  ceremony?: { [k: string]: Json }
  issuedAt: string
  payload: { [k: string]: Json }
  proof?: ({
    type: "DataIntegrityProof"
    cryptosuite: "eddsa-jcs-2022"
    created: string
    verificationMethod: string
    proofPurpose: "assertionMethod"
    proofValue: string
  }) | ({
    mac: string
  })
})

/** schemas/sealed-envelope.schema.json — RLTP Sealed Envelope (rltp-delivery@0.79) */
export type SealedEnvelope = {
  rkid: string
  epk: string
  nonce: string
  ciphertext: string
}

/** schemas/visibility-anchor-mapping.schema.json — RLTP anchor-mapping@2 (rltp-visibility@0.29) */
export type VisibilityAnchorMapping = {
  body: {
    type: "anchor-mapping@2"
    pair: string
    self: string
    to: string
    card: {
      body: {
        type: "self-card@1"
        anchor: string
        keyAgreement: string
      }
      proof: {
        proofValue: string
      }
    }
    revision: string
    issuedAt: string
  }
  proof: {
    mac1: string
    mac2: string
  }
}

/** schemas/visibility-continuity-mapping.schema.json — RLTP continuity-mapping@1 (rltp-visibility@0.29) */
export type VisibilityContinuityMapping = {
  body: {
    type: "continuity-mapping@1"
    prior: string
    next: string
    to: string
    revision: string
    issuedAt: string
  }
  proof: {
    mac1: string
    mac2: string
  }
}

/** schemas/visibility-continuity-probe.schema.json — RLTP continuity-probe@1 (rltp-visibility@0.29) */
export type VisibilityContinuityProbe = {
  body: {
    type: "continuity-probe@1"
    probe: string
    seq: string
    last: boolean
    blinded: string[]
  }
  proof: {
    mac: string
  }
}

/** schemas/visibility-grade-declaration.schema.json — RLTP grade-declaration@1 (rltp-visibility@0.29) */
export type VisibilityGradeDeclaration = {
  body: {
    type: "grade-declaration@1"
    subject: string
    holder: string
    grade: "count" | "blinded"
    revision: string
    issuedAt: string
  }
  proof: {
    mac: string
  }
}

/** schemas/visibility-introduction-ack.schema.json — RLTP introduction-ack@1 (rltp-visibility@0.29) */
export type VisibilityIntroductionAck = {
  body: {
    type: "introduction-ack@1"
    act: string
  }
  proof: {
    mac: string
  }
}

/** schemas/visibility-introduction-reply.schema.json — RLTP introduction-reply@1 (rltp-visibility@0.29) */
export type VisibilityIntroductionReply = {
  body: {
    type: "introduction-reply@1"
    act: string
    requestDigest: string
    requesterPair: string
    cardDigest: string
  }
  proof: {
    proofValue: string
  }
}

/** schemas/visibility-introduction-request.schema.json — RLTP introduction-request@1 (rltp-visibility@0.29) */
export type VisibilityIntroductionRequest = {
  body: {
    type: "introduction-request@1"
    act: string
    issuedAt: string
    target: string
    cardDigest: string
    profile: {
      displayName?: string
      note?: string
    }
  }
  proof: {
    proofValue: string
  }
}

/** schemas/visibility-introduction-voucher.schema.json — RLTP introduction-voucher@1 (rltp-visibility@0.29) */
export type VisibilityIntroductionVoucher = {
  body: {
    type: "introduction-voucher@1"
    act: string
    requesterPair: string
    targetPair: string
  }
  proof: {
    mac: string
  }
}

/** schemas/visibility-payload-introduction-ack.schema.json — RLTP payload introduction-ack (rltp-visibility@0.29) */
export type VisibilityPayloadIntroductionAck = {
  introduction: VisibilityIntroductionAck
}

/** schemas/visibility-payload-introduction-forward.schema.json — RLTP payload introduction-forward (rltp-visibility@0.29) — byte-identical to the request payload */
export type VisibilityPayloadIntroductionForward = {
  introduction: VisibilityIntroductionRequest
  card: ContactCard025
}

/** schemas/visibility-payload-introduction-reply.schema.json — RLTP payload introduction-reply (rltp-visibility@0.29) */
export type VisibilityPayloadIntroductionReply = {
  introduction: VisibilityIntroductionReply
  card: ContactCard025
}

/** schemas/visibility-payload-introduction-request.schema.json — RLTP payload introduction-request (rltp-visibility@0.29) */
export type VisibilityPayloadIntroductionRequest = {
  introduction: VisibilityIntroductionRequest
  card: ContactCard025
}

/** schemas/visibility-payload-introduction-voucher.schema.json — RLTP payload introduction-voucher (rltp-visibility@0.29) */
export type VisibilityPayloadIntroductionVoucher = {
  voucher: VisibilityIntroductionVoucher
}

/** schemas/visibility-self-card.schema.json — RLTP self-card@1 (rltp-visibility@0.29) */
export type VisibilitySelfCard = {
  body: {
    type: "self-card@1"
    anchor: string
    keyAgreement: string
  }
  proof: {
    proofValue: string
  }
}

/** schemas/visibility-star.schema.json — RLTP star@1 (rltp-visibility@0.29) */
export type VisibilityStar = {
  body: {
    type: "star@1"
    salt: string
    seq: string
    last: boolean
    count: string
    blinded: string[]
  }
  proof: {
    mac: string
  }
}

/** schemas/welcome.schema.json — RLTP Welcome (rltp-welcome/0.1, rltp-membership@0.17) */
export type Welcome = {
  v: "rltp-welcome/0.1"
  group: string
  subject: string
  accept: string
  material: (AccessMaterial) & ({
    v?: "rltp-access-material/0.25"
  })
}
